FROM {{ inherits }}
WORKDIR /texbld
{% if packages|length > 0 %}RUN {{ update }}
RUN {{ install }}{% for  package in packages %} {{ package }}{% endfor %} {%endif%} {% for source,target in files.items() %}
COPY {{source}} {{target}} {% endfor %} {% for command in setup %} 
RUN {{ command }} {% endfor %}