name: Nightly Zipapp builds
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  build:
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: cachix/install-nix-action@v20
      - run: nix build .#zipapp
      - run: cp -Lr result out
      - name: Delete nightly release
        run: gh release delete nightly --yes || true
      - name: Upload to releases
        run: |
          gh release create nightly --prerelease --title "TeXbld Nightly Build" --target $GITHUB_SHA out/*
